__import__('modules.operators.addition')
__import__('modules.operators.and')
__import__('modules.operators.division')
__import__('modules.operators.multiplication')
__import__('modules.operators.or')
__import__('modules.operators.subtraction')

__import__('modules.operators.equal')
__import__('modules.operators.notequal')
__import__('modules.operators.lessthan')
__import__('modules.operators.greaterthan')
__import__('modules.operators.lessorequal')
__import__('modules.operators.greaterorequal')
__import__('modules.operators.overlap')